FROM node:18

WORKDIR /app

# Копіюємо файли залежностей і встановлюємо їх
COPY frontend/package*.json ./
RUN npm install

# Копіюємо увесь код фронтенду
COPY frontend/ ./

# Збираємо додаток у production режимі
RUN npm run build --prod

# Відкриваємо порт 4200
EXPOSE 4200

# Запускаємо сервер для подачі статичних файлів (наприклад, через http-server)
CMD ["npx", "http-server", "dist/frontend/browser", "-p", "4200"]
