FROM node:18
WORKDIR /app
COPY frontend/angular_app/package*.json ./
RUN npm install
COPY frontend/angular_app /app
RUN npm run build --prod
CMD ["npx", "http-server", "dist/angular_app", "-p", "4200"]
