version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: django_app
    # "expose" робить порт доступним всередині мережі Docker, але не публікує його на хост
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: angular_app
    ports:
      - "4200:4200"
    depends_on:
      - backend