FROM python:3.9

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Копіюємо файли з вимогами та встановлюємо залежності
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо код бекенду
COPY backend/ /app

# Запускаємо сервер Django на 0.0.0.0:8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
